### ISSUE TITLE
CSS Selectors naming need to refactored with better convention

### ISSUE THREAD

**Issue by umanda** [textualworks/lanka-icons#1]
I have seen there will be a chance to improve naming conventions of LS fonts. I would prefer to do as follows

starAndCrescent >  star-and-crescent

wheelOfDharma > wheel-of-dharma

lks-lkflaglion >   lks-lk-flag-lion

lks-flaglion-outline >  ls lks-lk-flag-lion-o

**Comment by chathurabuddi** [comment]
@pathumego , please review the pull request
